name: Linting

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  golangci:
    name: Linting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Generate rest models
        run: make rest/models/model_component.go

      - name: Run linter
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.49.0
